### ISSUE TITLE
[Core DSL] para

### ISSUE THREAD

**Issue by Schwad** [Schwad/scarpe#1]
`para` 

<details>
  <summary>From the canonical manual</summary>
<img width="430" alt="Screenshot 2023-02-03 at 10 59 45" src="https://user-images.githubusercontent.com/7865030/216587286-17b25e3f-1759-489f-a325-d68dc1c673ba.png">
<img width="430" alt="Screenshot 2023-02-03 at 10 59 54" src="https://user-images.githubusercontent.com/7865030/216587314-87f543f6-5e61-4934-863a-1f96f1c786ee.png">
</details>

"Para" returns text. We're also including other text rendering methods in this issue such as "subtitle", "caption", etc.

### Tasklist
  - [x] Initialize within the gem
  - [x] Migrate `def render` to use our native HTML renderer
  - [x] Support a collection of arguments, joined into one string.
    * e.g. `para 'this', 'is', 'a', 'string'`
  - [x] `stroke` kwarg to add color @christhesoul 
  - #### Methods to add
    - [x] `banner`; 48px
    - [x] `title`; 34px
    - [x] `subtitle`; 26px;
    - [ ] `tagline`; 18px;
    - [x] `caption`; 14px;
    - [x] `para`; 12px;
    - [ ] `inscription`; 10px;
      - [ ] Alias `ins` for `inscription`
  - #### Options
    - [x] `size` @DRBragg 
      * Manually resize this text: e.g. `para 'hi', size: 34`
      * Like their HTML counterparts
    * e.g. `para "hello", strong("dude"), em("how's it going?")`
    - [x] `strong`
    - [x] `em`
    - [x] `code`

**Comment by DRBragg** [comment]
The `size` option seems like a nice way to ease in. I'll tackle that first

**Comment by gajewsky** [comment]
@DRBragg FYI there is open PR which will make adding `size` easy

**Comment by DRBragg** [comment]
#55 handles the size option. Should make the size methods fairly easy
