### ISSUE TITLE
Introducing Widgets, and Widget Refactor

### ISSUE THREAD

**Issue by Schwad** [Schwad/scarpe#43]
## Background

Widgets are a native part of Shoes that allows users composability like so:

<details>
<summary>
See full code snippet
</summary>

```ruby
class MenuPanel < Shoes::Widget
  @@boxes = []
  def initialize(color, args)
    @@boxes << self
    background color
    para link("Box #{@@boxes.length}", :stroke => white, :fill => nil).
      click { visit "/" },
        :margin => 18, :align => "center", :size => 20
    hover { expand }
  end
  def expand
    if self.width < 170
      a = animate 30 do
        @@boxes.each do |b|
          b.width -= 5 if b != self and b.width > 140
        end
        self.width += 5
        a.stop if self.width >= 170
      end
    end
  end
end

Shoes.app :width => 400, :height => 130 do
  style(Link, :underline => nil)
  style(LinkHover, :fill => nil, :underline => nil)
  menu_panel green,  :width => 170, :height => 120, :margin => 4
  menu_panel blue,   :width => 140, :height => 120, :margin => 4
  menu_panel red,    :width => 140, :height => 120, :margin => 4
  menu_panel purple, :width => 140, :height => 120, :margin => 4
end
```

</details>

This also gives us the ability to define a more controlled internal API for us to build our _own_ widgets (e.g. `para`, `image`), and DRY them up. Imagine something like this:

```ruby
module Scarpe
  class Image < Scarpe::Widget
    def render(url)
      HTML.render do |h|
        h.img(src: url)
      end
    end
  end
end
```

Where we can get rid of initializer (unless needed with Super)

This will also involve a larger refactor of some of our internals. There are a few steps, which include migrating some of our internal widgets where possible (though not necessary during hackdays!). This will also help us prevent further issues

## Tasklist from pairing session

1. Create widget parent class
  * obvious accessors we know we need
* Convert at least one existing feature to inherit from widget
  * e.g. `class Para < Scarpe::Widget`
  * If you inherit from widget you can remove initialize, or at least `super` it
1. Convert more difficult widgets
1. Remove :attr_reader :window, and @app becomes app
1. Removing parts of the interface that are problematic (e.g. stop passing in the webview)
1. Building an AST out of Shoes::Widget components and then rendering that.

**Comment by Schwad** [comment]
@CalvinWalzel has indicated he will take an initial look at this and then @noahgibbs and I will pair on this in the morning together with Calvin.

Please correct me if I'm misrepresenting something 🙇

**Comment by noahgibbs** [comment]
We have this, though the API isn't exactly the same. It is *not* compatible with the old Shoes widget API, which we should go look up. But it's not gonna as long as we're rendering HTML :-) So I think this is fixed.
