### ISSUE TITLE
Discord improvements

### ISSUE THREAD

**Issue by CalvinWalzel** [Schwad/scarpe#51]
- [x] Add an `#ops` channel in Discord
  - We can use webhooks to achieve this easily: [Link](https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22)
- [x] Add a collaborator role
- [x] Add an invite link to Readme.md (no expiration date)
  - [x] Security harden the Discord (important)

**Comment by Schwad** [comment]
This is a good idea. I want to keep the channels slim but I think ops makes sense
