### ISSUE TITLE
[Core DSL] edit_box

### ISSUE THREAD

**Issue by Schwad** [Schwad/scarpe#7]
`edit_line` 

<details>
  <summary>From the canonical manual</summary>
<img width="440" alt="Screenshot 2023-02-03 at 12 06 04" src="https://user-images.githubusercontent.com/7865030/217540540-7e9d7a77-8a59-492d-be38-a0f80a43312b.png">

</details>

This is similar to `edit_line` but it has height and a scrollbar it may deploy

### Tasklist
  - [ ] Accept text argument for default pre-filled data
  - [ ] Initialize within the gem
  - [ ] unit testing
  - [ ] `width`
  - [ ] `height`
  - [ ] returns an object with a text property, like so:
    * `@e = edit_line width: 400; @e.text #=> 'huzzah!'`
    * This object can be used elsewhere and reset with `@e.text =`

**Comment by DRBragg** [comment]
@Schwad Looks like the manual screenshot didn't get uploaded. Do you have a link to the manual or can you try uploading again?

**Comment by DRBragg** [comment]
I'll work on this while para is being updated

**Comment by Schwad** [comment]
@DRBragg shoot sorry, here's the manual!

<img width="440" alt="Screenshot 2023-02-03 at 12 06 04" src="https://user-images.githubusercontent.com/7865030/217540540-7e9d7a77-8a59-492d-be38-a0f80a43312b.png">
